--
-- PostgreSQL database cluster dump
--

-- Started on 2024-06-18 00:14:09

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2024-06-18 00:14:10

--
-- PostgreSQL database dump complete
--

--
-- Database "Optativo5" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4858 (class 1262 OID 16521)
-- Name: Optativo5; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Optativo5" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "Optativo5" OWNER TO postgres;

\connect "Optativo5"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16528)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "Id" integer NOT NULL,
    "Id_banco" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Documento" text NOT NULL,
    "Direccion" text NOT NULL,
    "Mail" text NOT NULL,
    "Celular" text NOT NULL,
    "Estado" text NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16527)
-- Name: Clientes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16536)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "Id" integer NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Nro_factura" text NOT NULL,
    "Fecha_hora" text NOT NULL,
    "Total" text NOT NULL,
    "Total_iva" text NOT NULL,
    "Total_iva10" text NOT NULL,
    "Total_iva5" text NOT NULL,
    "Total_letras" character varying(6) NOT NULL,
    "Sucursal" text NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16535)
-- Name: Facturas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16522)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 16528)
-- Dependencies: 217
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clientes" ("Id", "Id_banco", "Nombre", "Apellido", "Documento", "Direccion", "Mail", "Celular", "Estado") FROM stdin;
\.


--
-- TOC entry 4852 (class 0 OID 16536)
-- Dependencies: 219
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("Id", "Id_cliente", "Nro_factura", "Fecha_hora", "Total", "Total_iva", "Total_iva10", "Total_iva5", "Total_letras", "Sucursal") FROM stdin;
\.


--
-- TOC entry 4848 (class 0 OID 16522)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240522030104_MigracionInicial	6.0.22
\.


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 216
-- Name: Clientes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_Id_seq"', 1, false);


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 218
-- Name: Facturas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_Id_seq"', 1, false);


--
-- TOC entry 4700 (class 2606 OID 16534)
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id");


--
-- TOC entry 4703 (class 2606 OID 16542)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id");


--
-- TOC entry 4698 (class 2606 OID 16526)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4701 (class 1259 OID 16548)
-- Name: IX_Facturas_Id_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Facturas_Id_cliente" ON public."Facturas" USING btree ("Id_cliente");


--
-- TOC entry 4704 (class 2606 OID 16543)
-- Name: Facturas FK_Facturas_Clientes_Id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "FK_Facturas_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES public."Clientes"("Id") ON DELETE CASCADE;


-- Completed on 2024-06-18 00:14:10

--
-- PostgreSQL database dump complete
--

--
-- Database "OptativoSegundo" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4858 (class 1262 OID 16606)
-- Name: OptativoSegundo; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "OptativoSegundo" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "OptativoSegundo" OWNER TO postgres;

\connect "OptativoSegundo"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16613)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "Id" integer NOT NULL,
    "Id_banco" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Documento" text NOT NULL,
    "Direccion" text NOT NULL,
    "Mail" text NOT NULL,
    "Celular" text NOT NULL,
    "Estado" text NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16612)
-- Name: Clientes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16621)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "Id" integer NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Nro_factura" text NOT NULL,
    "Fecha_hora" text NOT NULL,
    "Total" text NOT NULL,
    "Total_iva" text NOT NULL,
    "Total_iva10" text NOT NULL,
    "Total_iva5" text NOT NULL,
    "Total_letras" character varying(6) NOT NULL,
    "Sucursal" text NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16620)
-- Name: Facturas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16607)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 16613)
-- Dependencies: 217
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clientes" ("Id", "Id_banco", "Nombre", "Apellido", "Documento", "Direccion", "Mail", "Celular", "Estado") FROM stdin;
\.


--
-- TOC entry 4852 (class 0 OID 16621)
-- Dependencies: 219
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("Id", "Id_cliente", "Nro_factura", "Fecha_hora", "Total", "Total_iva", "Total_iva10", "Total_iva5", "Total_letras", "Sucursal") FROM stdin;
\.


--
-- TOC entry 4848 (class 0 OID 16607)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240522030903_MigracionInicial	6.0.22
\.


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 216
-- Name: Clientes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_Id_seq"', 1, false);


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 218
-- Name: Facturas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_Id_seq"', 1, false);


--
-- TOC entry 4700 (class 2606 OID 16619)
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id");


--
-- TOC entry 4703 (class 2606 OID 16627)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id");


--
-- TOC entry 4698 (class 2606 OID 16611)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4701 (class 1259 OID 16633)
-- Name: IX_Facturas_Id_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Facturas_Id_cliente" ON public."Facturas" USING btree ("Id_cliente");


--
-- TOC entry 4704 (class 2606 OID 16628)
-- Name: Facturas FK_Facturas_Clientes_Id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "FK_Facturas_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES public."Clientes"("Id") ON DELETE CASCADE;


-- Completed on 2024-06-18 00:14:10

--
-- PostgreSQL database dump complete
--

--
-- Database "OptativoV" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4858 (class 1262 OID 16549)
-- Name: OptativoV; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "OptativoV" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "OptativoV" OWNER TO postgres;

\connect "OptativoV"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16556)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "Id" integer NOT NULL,
    "Id_banco" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Documento" text NOT NULL,
    "Direccion" text NOT NULL,
    "Mail" text NOT NULL,
    "Celular" text NOT NULL,
    "Estado" text NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16555)
-- Name: Clientes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16564)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "Id" integer NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Nro_factura" text NOT NULL,
    "Fecha_hora" text NOT NULL,
    "Total" text NOT NULL,
    "Total_iva" text NOT NULL,
    "Total_iva10" text NOT NULL,
    "Total_iva5" text NOT NULL,
    "Total_letras" character varying(6) NOT NULL,
    "Sucursal" text NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16563)
-- Name: Facturas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16550)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 16556)
-- Dependencies: 217
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clientes" ("Id", "Id_banco", "Nombre", "Apellido", "Documento", "Direccion", "Mail", "Celular", "Estado") FROM stdin;
\.


--
-- TOC entry 4852 (class 0 OID 16564)
-- Dependencies: 219
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("Id", "Id_cliente", "Nro_factura", "Fecha_hora", "Total", "Total_iva", "Total_iva10", "Total_iva5", "Total_letras", "Sucursal") FROM stdin;
\.


--
-- TOC entry 4848 (class 0 OID 16550)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240522030404_MigracionInicial	6.0.22
\.


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 216
-- Name: Clientes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_Id_seq"', 1, false);


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 218
-- Name: Facturas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_Id_seq"', 1, false);


--
-- TOC entry 4700 (class 2606 OID 16562)
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id");


--
-- TOC entry 4703 (class 2606 OID 16570)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id");


--
-- TOC entry 4698 (class 2606 OID 16554)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4701 (class 1259 OID 16576)
-- Name: IX_Facturas_Id_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Facturas_Id_cliente" ON public."Facturas" USING btree ("Id_cliente");


--
-- TOC entry 4704 (class 2606 OID 16571)
-- Name: Facturas FK_Facturas_Clientes_Id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "FK_Facturas_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES public."Clientes"("Id") ON DELETE CASCADE;


-- Completed on 2024-06-18 00:14:10

--
-- PostgreSQL database dump complete
--

--
-- Database "SegundoParcial" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4858 (class 1262 OID 16577)
-- Name: SegundoParcial; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "SegundoParcial" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "SegundoParcial" OWNER TO postgres;

\connect "SegundoParcial"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16584)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "Id" integer NOT NULL,
    "Id_banco" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Documento" text NOT NULL,
    "Direccion" text NOT NULL,
    "Mail" text NOT NULL,
    "Celular" text NOT NULL,
    "Estado" text NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16583)
-- Name: Clientes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16592)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "Id" integer NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Nro_factura" text NOT NULL,
    "Fecha_hora" text NOT NULL,
    "Total" text NOT NULL,
    "Total_iva" text NOT NULL,
    "Total_iva10" text NOT NULL,
    "Total_iva5" text NOT NULL,
    "Total_letras" character varying(6) NOT NULL,
    "Sucursal" text NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16591)
-- Name: Facturas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16578)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4850 (class 0 OID 16584)
-- Dependencies: 217
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clientes" ("Id", "Id_banco", "Nombre", "Apellido", "Documento", "Direccion", "Mail", "Celular", "Estado") FROM stdin;
\.


--
-- TOC entry 4852 (class 0 OID 16592)
-- Dependencies: 219
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("Id", "Id_cliente", "Nro_factura", "Fecha_hora", "Total", "Total_iva", "Total_iva10", "Total_iva5", "Total_letras", "Sucursal") FROM stdin;
\.


--
-- TOC entry 4848 (class 0 OID 16578)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240522030607_MigracionInicial	6.0.22
\.


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 216
-- Name: Clientes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_Id_seq"', 1, false);


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 218
-- Name: Facturas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_Id_seq"', 1, false);


--
-- TOC entry 4700 (class 2606 OID 16590)
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id");


--
-- TOC entry 4703 (class 2606 OID 16598)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id");


--
-- TOC entry 4698 (class 2606 OID 16582)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4701 (class 1259 OID 16604)
-- Name: IX_Facturas_Id_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Facturas_Id_cliente" ON public."Facturas" USING btree ("Id_cliente");


--
-- TOC entry 4704 (class 2606 OID 16599)
-- Name: Facturas FK_Facturas_Clientes_Id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "FK_Facturas_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES public."Clientes"("Id") ON DELETE CASCADE;


-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database dump complete
--

--
-- Database "mauriexamen" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4853 (class 1262 OID 16398)
-- Name: mauriexamen; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE mauriexamen WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE mauriexamen OWNER TO postgres;

\connect mauriexamen

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    id_banco character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    apellido character varying(255) NOT NULL,
    documento character varying(255) NOT NULL,
    mail character varying(255) NOT NULL,
    celular character varying(255) NOT NULL,
    estado character varying DEFAULT true NOT NULL
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cliente_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 4854 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cliente_id_seq OWNED BY public.cliente.id;


--
-- TOC entry 217 (class 1259 OID 16447)
-- Name: factura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.factura_id_seq OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16448)
-- Name: factura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.factura (
    id integer DEFAULT nextval('public.factura_id_seq'::regclass) NOT NULL,
    id_cliente integer NOT NULL,
    nro_factura character varying(255) NOT NULL,
    fecha_hora character varying(255) NOT NULL,
    total character varying(255) NOT NULL,
    total_iva5 character varying(255) NOT NULL,
    total_iva10 character varying(255) NOT NULL,
    total_iva character varying(255) NOT NULL,
    total_letras character varying(255) NOT NULL,
    sucursal character varying(255) NOT NULL
);


ALTER TABLE public.factura OWNER TO postgres;

--
-- TOC entry 4693 (class 2604 OID 16403)
-- Name: cliente id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente ALTER COLUMN id SET DEFAULT nextval('public.cliente_id_seq'::regclass);


--
-- TOC entry 4845 (class 0 OID 16400)
-- Dependencies: 216
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, id_banco, nombre, apellido, documento, mail, celular, estado) FROM stdin;
0	0	das	das	dsa	da	da	da
1	10	string	string	string	string	string	string
3	0	xaaaaaaaaaad	string	string	string	string	string
\.


--
-- TOC entry 4847 (class 0 OID 16448)
-- Dependencies: 218
-- Data for Name: factura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.factura (id, id_cliente, nro_factura, fecha_hora, total, total_iva5, total_iva10, total_iva, total_letras, sucursal) FROM stdin;
1	0	123-456-789123	string	3123445	12345	12345	12345	string	string
\.


--
-- TOC entry 4855 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 3, true);


--
-- TOC entry 4856 (class 0 OID 0)
-- Dependencies: 217
-- Name: factura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.factura_id_seq', 1, true);


--
-- TOC entry 4697 (class 2606 OID 16408)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 16455)
-- Name: factura factura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id);


--
-- TOC entry 4700 (class 2606 OID 16456)
-- Name: factura fk_id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_id_cliente FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16662)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 4857 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16698)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "Id" integer NOT NULL,
    "Id_banco" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Documento" text NOT NULL,
    "Direccion" text NOT NULL,
    "Mail" text NOT NULL,
    "Celular" text NOT NULL,
    "Estado" text NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16697)
-- Name: Clientes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16706)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "Id" integer NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Nro_factura" text NOT NULL,
    "Fecha_hora" text NOT NULL,
    "Total" integer NOT NULL,
    "Total_iva" integer NOT NULL,
    "Total_iva10" integer NOT NULL,
    "Total_iva5" integer NOT NULL,
    "Total_letras" text NOT NULL,
    "Sucursal" text NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16705)
-- Name: Facturas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16692)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4849 (class 0 OID 16698)
-- Dependencies: 218
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clientes" ("Id", "Id_banco", "Nombre", "Apellido", "Documento", "Direccion", "Mail", "Celular", "Estado") FROM stdin;
8	0	string	string	string	string	string	string	string
9	0	string	string	string	string	string	string	string
10	0	string	string	6587520	string	string@gmail.com	0992233050	Activo
6	0	string	string	6587528	string	string@gmail.com	0992233050	Activo
\.


--
-- TOC entry 4851 (class 0 OID 16706)
-- Dependencies: 220
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("Id", "Id_cliente", "Nro_factura", "Fecha_hora", "Total", "Total_iva", "Total_iva10", "Total_iva5", "Total_letras", "Sucursal") FROM stdin;
6	0	292-429-120448	string	10	1	10	10	123456	string
7	0	618-957-993493	string	10	10	10	10	string	string
8	1	344-650-744370	string	10	10	10	10	string	string
5	3	135-336-093564	string	10	10	10	10	string	string
\.


--
-- TOC entry 4847 (class 0 OID 16692)
-- Dependencies: 216
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240522062918_MigracionInicial	6.0.30
20240522063305_MigracionDos	6.0.30
\.


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 217
-- Name: Clientes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_Id_seq"', 10, true);


--
-- TOC entry 4861 (class 0 OID 0)
-- Dependencies: 219
-- Name: Facturas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_Id_seq"', 8, true);


--
-- TOC entry 4701 (class 2606 OID 16704)
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id");


--
-- TOC entry 4703 (class 2606 OID 16712)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id");


--
-- TOC entry 4699 (class 2606 OID 16696)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4858 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database dump complete
--

--
-- Database "primerparcial" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4852 (class 1262 OID 16461)
-- Name: primerparcial; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE primerparcial WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE primerparcial OWNER TO postgres;

\connect primerparcial

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16463)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    id_banco integer NOT NULL,
    nombre character varying(255) NOT NULL,
    apellido character varying(255) NOT NULL,
    documento character varying(255) NOT NULL,
    direccion character varying(255) NOT NULL,
    mail character varying(255) NOT NULL,
    celular character varying(255) NOT NULL,
    estado character varying(255) NOT NULL
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16462)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cliente_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 4853 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cliente_id_seq OWNED BY public.cliente.id;


--
-- TOC entry 218 (class 1259 OID 16472)
-- Name: factura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.factura (
    id integer NOT NULL,
    id_cliente integer NOT NULL,
    nro_factura character varying(255) NOT NULL,
    fecha_hora character varying(255) NOT NULL,
    total character varying(255) NOT NULL,
    total_iva5 character varying(255) NOT NULL,
    total_iva10 character varying(255) NOT NULL,
    total_iva character varying(255) NOT NULL,
    total_letras character varying(255) NOT NULL,
    sucursal character varying(255) NOT NULL
);


ALTER TABLE public.factura OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16471)
-- Name: factura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.factura_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.factura_id_seq OWNER TO postgres;

--
-- TOC entry 4854 (class 0 OID 0)
-- Dependencies: 217
-- Name: factura_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.factura_id_seq OWNED BY public.factura.id;


--
-- TOC entry 4693 (class 2604 OID 16466)
-- Name: cliente id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente ALTER COLUMN id SET DEFAULT nextval('public.cliente_id_seq'::regclass);


--
-- TOC entry 4694 (class 2604 OID 16475)
-- Name: factura id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.factura ALTER COLUMN id SET DEFAULT nextval('public.factura_id_seq'::regclass);


--
-- TOC entry 4844 (class 0 OID 16463)
-- Dependencies: 216
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, id_banco, nombre, apellido, documento, direccion, mail, celular, estado) FROM stdin;
2	0	mauricio	ramirez	6587520	comandante caballero 1131	mauriciormirez09@gmail.com	0992233050	prueba
\.


--
-- TOC entry 4846 (class 0 OID 16472)
-- Dependencies: 218
-- Data for Name: factura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.factura (id, id_cliente, nro_factura, fecha_hora, total, total_iva5, total_iva10, total_iva, total_letras, sucursal) FROM stdin;
2	2	501-153-320686	string	23184802695332467624	683447948097833916657041693137942793.00	78682909840891788061967017956587961467488147113025179941041270600915472858.48	47745176190579719058.12	string	string
\.


--
-- TOC entry 4855 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 2, true);


--
-- TOC entry 4856 (class 0 OID 0)
-- Dependencies: 217
-- Name: factura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.factura_id_seq', 2, true);


--
-- TOC entry 4696 (class 2606 OID 16470)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 4698 (class 2606 OID 16479)
-- Name: factura factura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 16480)
-- Name: factura fk_id_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_id_cliente FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database dump complete
--

--
-- Database "primerparcial_mauri" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 00:14:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4831 (class 1262 OID 16491)
-- Name: primerparcial_mauri; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE primerparcial_mauri WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE primerparcial_mauri OWNER TO postgres;

\connect primerparcial_mauri

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database dump complete
--

-- Completed on 2024-06-18 00:14:11

--
-- PostgreSQL database cluster dump complete
--

